import { LandRecord, Transaction } from './types';

export const TRANSLATIONS = {
  en: {
    appTitle: "LandChain",
    connectWallet: "Connect Wallet",
    disconnect: "Disconnect",
    navHome: "Home",
    navRegister: "Register Land",
    navSearch: "Search Records",
    navAdmin: "Admin Dashboard",
    navGovtRecords: "All Records",
    step1: "Property Details",
    step2: "Owner Information",
    step3: "Document Upload",
    step4: "Review & Submit",
    next: "Next",
    back: "Back",
    submit: "Submit to Blockchain",
    division: "Division",
    district: "District",
    surveyNo: "Kadastro No (TD/TS/TK)",
    area: "Area Size",
    unit: "Unit",
    lat: "Latitude",
    lng: "Longitude",
    ownerName: "Owner Name",
    nid: "National ID No",
    uploadDeed: "Upload Title Deed (PDF/Image)",
    reviewTitle: "Review Information",
    searchPlaceholder: "Enter Land UID, Owner Address, or Survey No",
    searchButton: "Verify Land",
    verified: "Verified",
    pending: "Pending Verification",
    ownershipHistory: "Ownership History",
    redFlag: "RED FLAG: Suspicious Activity Detected",
    adminQueue: "Verification Queue",
    approve: "Approve",
    reject: "Reject",
    gasFee: "Est. Gas Fee",
  },
  tr: {
    appTitle: "LandChain",
    connectWallet: "Cüzdan Bağla",
    disconnect: "Bağlantıyı Kes",
    navHome: "Ana Sayfa",
    navRegister: "Arazi Kaydı",
    navSearch: "Kayıt Ara",
    navAdmin: "Yönetici Paneli",
    navGovtRecords: "Tüm Kayıtlar",
    step1: "Mülk Detayları",
    step2: "Sahip Bilgileri",
    step3: "Belge Yükleme",
    step4: "İncele ve Gönder",
    next: "İleri",
    back: "Geri",
    submit: "Blockchain'e Gönder",
    division: "Bölge",
    district: "İlçe",
    surveyNo: "Kadastro No (TD/TS/TK)",
    area: "Alan Büyüklüğü",
    unit: "Birim",
    lat: "Enlem",
    lng: "Boylam",
    ownerName: "Malik Adı",
    nid: "Kimlik Numarası",
    uploadDeed: "Tapu Belgesi Yükle (PDF/Resim)",
    reviewTitle: "Bilgileri İncele",
    searchPlaceholder: "Arazi UID, Sahip Adresi veya Kadastro No Girin",
    searchButton: "Araziyi Doğrula",
    verified: "Doğrulandı",
    pending: "Doğrulama Bekliyor",
    ownershipHistory: "Sahiplik Geçmişi",
    redFlag: "KIRMIZI BAYRAK: Şüpheli Aktivite Tespit Edildi",
    adminQueue: "Doğrulama Kuyruğu",
    approve: "Onayla",
    reject: "Reddet",
    gasFee: "Tahmini Gaz Ücreti",
  }
};

export const MOCK_LAND_RECORDS: LandRecord[] = [
  {
    landUid: "LND-8829-IST",
    ownerAddress: "0x71C7656EC7ab88b098defB751B7401B5f6d8976F",
    ownerName: "Mehmet Yılmaz",
    surveyNumber: "TD-1029",
    division: "İstanbul",
    district: "Kadıköy",
    area: { value: 500, unit: "metrekare" },
    gpsCoordinates: { lat: 41.0082, lng: 28.9784 },
    documentHash: "QmHash123...",
    registrationDate: 1672531200000,
    isVerified: true,
    history: [
      { from: "0x000...", to: "0x71C...", date: 1672531200000, hash: "0xTx1..." }
    ]
  },
  {
    landUid: "LND-1102-ANK",
    ownerAddress: "0x32A...",
    ownerName: "Ayşe Demir",
    surveyNumber: "TD-5541",
    division: "Ankara",
    district: "Çankaya",
    area: { value: 2, unit: "dönüm" },
    gpsCoordinates: { lat: 39.9334, lng: 32.8597 },
    documentHash: "QmHash456...",
    registrationDate: 1680307200000,
    isVerified: false
  }
];

export const MOCK_TRANSACTIONS: Transaction[] = [
  {
    hash: "0xabc...123",
    from: "0xUser1...",
    to: "0xGov...",
    landUid: "LND-NEW-01",
    status: "confirmed",
    timestamp: Date.now() - 50000
  },
  {
    hash: "0xdef...456",
    from: "0xUser2...",
    to: "0xGov...",
    landUid: "LND-NEW-02",
    status: "pending",
    timestamp: Date.now()
  }
];
